
services:
  # Base de données PostgreSQL
  postgres:
    container_name: book-network-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpassword
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_network_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - book-network
    restart: unless-stopped

  # Serveur de mail pour le développement
  maildev:
    container_name: book-network-maildev
    image: maildev/maildev
    ports:
      - "1080:1080"  # Interface web pour voir les emails
      - "1025:1025"  # Port SMTP
    networks:
      - book-network
    restart: unless-stopped

#  # Adminer - Interface web pour gérer PostgreSQL (optionnel)
#  adminer:
#    container_name: book-network-adminer
#    image: adminer:latest
#    ports:
#      - "8090:8080"
#    environment:
#      ADMINER_DEFAULT_SERVER: postgres
#    networks:
#      - book-network
#    restart: unless-stopped
#    depends_on:
#      - postgres

# Volumes pour persister les données
volumes:
  postgres:
    driver: local

# Réseau pour la communication entre conteneurs
networks:
  book-network:
    driver: bridge