/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BookResponse } from '../models/book-response';
import { findAllBooks } from '../fn/book/find-all-books';
import { FindAllBooks$Params } from '../fn/book/find-all-books';
import { findAllBooksByOwner } from '../fn/book/find-all-books-by-owner';
import { FindAllBooksByOwner$Params } from '../fn/book/find-all-books-by-owner';
import { findAllBoroowedBooks } from '../fn/book/find-all-boroowed-books';
import { FindAllBoroowedBooks$Params } from '../fn/book/find-all-boroowed-books';
import { findBookById } from '../fn/book/find-book-by-id';
import { FindBookById$Params } from '../fn/book/find-book-by-id';
import { PageResponseBookResponse } from '../models/page-response-book-response';
import { PageResponseBorrowedBookResponse } from '../models/page-response-borrowed-book-response';
import { saveBook } from '../fn/book/save-book';
import { SaveBook$Params } from '../fn/book/save-book';

@Injectable({ providedIn: 'root' })
export class BookService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllBooks()` */
  static readonly FindAllBooksPath = '/books';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBooks$Response(params?: FindAllBooks$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponseBookResponse>> {
    const obs = findAllBooks(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBooks(params?: FindAllBooks$Params, context?: HttpContext): Promise<PageResponseBookResponse> {
    const resp = this.findAllBooks$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponseBookResponse>): PageResponseBookResponse => r.body);
  }

  /** Path part for operation `saveBook()` */
  static readonly SaveBookPath = '/books';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveBook()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBook$Response(params: SaveBook$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = saveBook(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveBook$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBook(params: SaveBook$Params, context?: HttpContext): Promise<number> {
    const resp = this.saveBook$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `findBookById()` */
  static readonly FindBookByIdPath = '/books/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findBookById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findBookById$Response(params?: FindBookById$Params, context?: HttpContext): Promise<StrictHttpResponse<BookResponse>> {
    const obs = findBookById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findBookById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findBookById(params?: FindBookById$Params, context?: HttpContext): Promise<BookResponse> {
    const resp = this.findBookById$Response(params, context);
    return resp.then((r: StrictHttpResponse<BookResponse>): BookResponse => r.body);
  }

  /** Path part for operation `findAllBooksByOwner()` */
  static readonly FindAllBooksByOwnerPath = '/books/owner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBooksByOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBooksByOwner$Response(params?: FindAllBooksByOwner$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponseBookResponse>> {
    const obs = findAllBooksByOwner(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBooksByOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBooksByOwner(params?: FindAllBooksByOwner$Params, context?: HttpContext): Promise<PageResponseBookResponse> {
    const resp = this.findAllBooksByOwner$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponseBookResponse>): PageResponseBookResponse => r.body);
  }

  /** Path part for operation `findAllBoroowedBooks()` */
  static readonly FindAllBoroowedBooksPath = '/books/borrowd';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBoroowedBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBoroowedBooks$Response(params?: FindAllBoroowedBooks$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponseBorrowedBookResponse>> {
    const obs = findAllBoroowedBooks(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBoroowedBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBoroowedBooks(params?: FindAllBoroowedBooks$Params, context?: HttpContext): Promise<PageResponseBorrowedBookResponse> {
    const resp = this.findAllBoroowedBooks$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponseBorrowedBookResponse>): PageResponseBorrowedBookResponse => r.body);
  }

}
